174,0
T,ModFrmHilD,ModFrmHilDElt,0
A,ModFrmHilD,13,Field,Integers,NarrowClassGroup,NarrowClassNumber,NarrowClassGroupMap,NarrowClassGroupRepresentatives,Level,Precision,Ideals,Dictionary,MultiplicationTable,Representatives,DictionaryRepresentatives
S,Print,,0,1,0,0,1,0,0,0,0,ModFrmHilD,,-38,-38,-38,-38,-38,-38
S,in,,0,2,0,0,0,0,0,0,0,ModFrmHilD,,0,0,-1,,36,-38,-38,-38,-38,-38
S,eq,True iff the two spaces of Hilbert modular forms are identically the same,0,2,0,0,0,0,0,0,0,ModFrmHilD,,0,0,ModFrmHilD,,36,-38,-38,-38,-38,-38
S,BaseField,The base field of the space M of Hilbert modular forms,0,1,0,0,0,0,0,0,0,ModFrmHilD,,-9,-38,-38,-38,-38,-38
S,Integers,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,215,-38,-38,-38,-38,-38
S,NarrowClassGroup,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,107,-38,-38,-38,-38,-38
S,NarrowClassNumber,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,148,-38,-38,-38,-38,-38
S,NarrowClassGroupMap,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,175,-38,-38,-38,-38,-38
S,NarrowClassGroupRepresentatives,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,175,-38,-38,-38,-38,-38
S,Level,The level of the space M of Hilbert modular forms,0,1,0,0,0,0,0,0,0,ModFrmHilD,,217,-38,-38,-38,-38,-38
S,Precision,The Precision of the space M of Hilbert modular forms,0,1,0,0,0,0,0,0,0,ModFrmHilD,,148,-38,-38,-38,-38,-38
S,Ideals,The Ideals of the space M of Hilbert modular forms,0,1,0,0,0,0,0,0,0,ModFrmHilD,,82,-38,-38,-38,-38,-38
S,Dictionary,The dictionary for ideals of the space M of Hilbert modular forms,0,1,0,0,0,0,0,0,0,ModFrmHilD,,457,-38,-38,-38,-38,-38
S,MultiplicationTable,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,82,-38,-38,-38,-38,-38
S,DictionaryRepresentatives,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,457,-38,-38,-38,-38,-38
S,Representatives,,0,1,0,0,0,0,0,0,0,ModFrmHilD,,82,-38,-38,-38,-38,-38
S,ModFrmHilDInitialize,Create an empty ModFrmHilD object,0,0,0,0,0,0,0,ModFrmHilD,-38,-38,-38,-38,-38
S,HMFSpace,Generates the space ModFrmHilD over F with level N,0,3,0,0,0,0,0,0,0,148,,0,0,217,,0,0,27,,ModFrmHilD,-38,-38,-38,-38,-38
S,ModFrmHilDCopy,new instance of ModFrmHilD,0,1,0,0,0,0,0,0,0,ModFrmHilD,,ModFrmHilD,-38,-38,-38,-38,-38
S,GetPosition,returns the position of ideal generated by nu,0,2,0,0,0,0,0,0,0,216,,0,0,ModFrmHilD,,148,-38,-38,-38,-38,-38
S,GetPosition,returns the position of ideal,0,2,0,0,0,0,0,0,0,217,,0,0,ModFrmHilD,,148,-38,-38,-38,-38,-38
S,HMFEquipWithMultiplication,Assign representatives and a dictionary for it to M,0,1,0,0,0,0,0,0,0,ModFrmHilD,,ModFrmHilD,-38,-38,-38,-38,-38
