// Cyclic cubic Hilbert modular threefold example from the q-expansions paper.
//
// Let F = Q(zeta_7 + zeta_7^-1), generated by a root of
// x^3 - x^2 - 2*x + 1.  Multiplication gives the
// full weight 8 space and a 7-dimensional subspace in weight 10, where
// Hecke operators at primes above 13 produce the missing directions.
//
// This example verifies the relevant trace-formula dimensions and the
// current q-expansion computation at finite precision.

procedure test_cyclic_cubic_threefold_products_and_hecke()
  Q := Rationals();
  R<x> := PolynomialRing(Q);
  F := NumberField(x^3 - x^2 - 2*x + 1);
  ZF := Integers(F);

  M := GradedRingOfHMFs(F, 1000);

  E := AssociativeArray();
  for k in [2, 4, 6, 8, 10] do
    Ek := EisensteinBasis(HMFSpace(M, [k, k, k]));
    assert #Ek eq 1;
    E[k] := Ek[1];
  end for;

  M8 := HMFSpace(M, [8, 8, 8]);
  assert EisensteinDimension(M8) eq 1;
  assert CuspDimension(M8) eq 4;
  assert Dimension(M8) eq 5;

  products8 := [
    E[2]^4,
    E[2]^2 * E[4],
    E[2] * E[6],
    E[4]^2,
    E[8]
  ];
  assert #LinearDependence(products8) eq 0;
  assert #products8 eq Dimension(M8);

  M10 := HMFSpace(M, [10, 10, 10]);
  assert EisensteinDimension(M10) eq 1;
  assert CuspDimension(M10) eq 8;
  assert Dimension(M10) eq 9;

  products10 := [
    E[2]^5,
    E[2]^3 * E[4],
    E[2]^2 * E[6],
    E[2] * E[4]^2,
    E[2] * E[8],
    E[4] * E[6],
    E[10]
  ];
  assert #LinearDependence(products10) eq 0;

  ps13 := [fac[1] : fac in Factorization(13*ZF)];
  assert #ps13 eq 3;
  assert &and[Norm(pp) eq 13 : pp in ps13];

  hecke_translates := [HeckeOperator(products10[1], pp) : pp in ps13];

  // Two primes above 13 give the two extra directions expected in M_10.
  assert #LinearDependence(products10 cat hecke_translates[1..2]) eq 0;
  assert #products10 + 2 eq Dimension(M10);
  assert #LinearDependence(products10 cat hecke_translates) eq 1;
end procedure;

test_cyclic_cubic_threefold_products_and_hecke();
