// Cyclic cubic Hilbert modular threefold example from the q-expansions paper.
//
// F = Q(zeta_7 + zeta_7^-1), generated by a root of x^3 - x^2 - 2*x + 1
// (discriminant 49, narrow class number 1).  The natural weight-graded model
// of the threefold uses the Eisenstein series E2, E4, E6, E8, E10 together
// with trace forms at two of the three split primes above 13: Eisenstein
// monomials span the full spaces through weight 8 and a 7-dimensional
// subspace of the 9-dimensional M_10, and the two trace forms supply the
// missing Galois-non-invariant directions AT FULL BASE PRECISION.  (Hecke
// translates, used by earlier versions of this example, reach the same two
// directions but with precision divided by Norm(p) = 13; the syzygies they
// produced were truncation artifacts, refuted in
// Tests/cyclic_cubic_threefold_regression.m with a pinned witness at norm 83.)
//
// Certified here at precision 300 (89 coefficient columns):
//   - trace-formula dimensions of M_k, k <= 16; Magma's builtin quaternionic
//     dimensions independently confirm weights 4, 6, 8 (the weight-8 builtin
//     run takes ~28 minutes and is not repeated here);
//   - rank(Eisenstein monomials + T(p13_1) + T(p13_2)) = 9 = dim M_10, so
//     coefficient truncation is injective on M_10 and the displayed linear
//     dependence of the third trace form is exact (conditional only on
//     dim M_10 = 9, a trace-formula upper bound);
//   - the seven map coordinates have algebraically independent monomial
//     evaluations in every weighted degree <= 16: full rank at any precision
//     rules out relations unconditionally, so the relation ideal is ZERO in
//     degrees <= 16 (the slow driver extends this through degree 24 at
//     precision 450 and through degree 26 at precision 700; free monomial
//     counts never exceed dim M_d through degree 40, with equality only up to
//     weight 10, so no pigeonhole ever forces relations in this range);
//   - the image is a threefold: Jacobian certificate for E2^4, E2^2*E4,
//     E2*E6, E8, whose ratios generate E4/E2^2, E6/E2^3, E8/E2^4.  Earlier
//     versions certified the quadruple E2^4, E2^2*E4, E2*E6, E4^2, which is
//     algebraically dependent ((E2^2*E4)^2 = E2^4 * E4^2) and passed only
//     through the AlgebraicallyIndependent soundness bug fixed alongside this
//     example (see Tests/algebraically_independent_soundness.m).

procedure test_cyclic_cubic_threefold()
  Q := Rationals();
  R<x> := PolynomialRing(Q);
  F := NumberField(x^3 - x^2 - 2*x + 1);
  ZF := Integers(F);

  assert NarrowClassNumber(F) eq 1;
  assert ComputePrecisionFromHilbertSeries(1*ZF, 8) eq 60;
  assert ComputePrecisionFromHilbertSeries(1*ZF, 10) eq 100;

  prec := 300;
  M := GradedRingOfHMFs(F, prec);

  E := AssociativeArray();
  for k in [2, 4, 6, 8, 10] do
    Ek := EisensteinBasis(HMFSpace(M, [k, k, k]));
    assert #Ek eq 1;
    E[k] := Ek[1];
  end for;

  // Trace-formula dimensions (builtin-confirmed at weights 4, 6, 8).
  expected_dims := [1, 2, 3, 5, 9, 17, 27, 41];
  for i in [1..8] do
    k := 2*i;
    Mk := HMFSpace(M, [k, k, k]);
    assert Dimension(Mk) eq expected_dims[i];
  end for;

  M8 := HMFSpace(M, [8, 8, 8]);
  assert EisensteinDimension(M8) eq 1;
  assert CuspDimension(M8) eq 4;

  // Eisenstein monomials span all of M_8: rank 5 = dim, so truncation is
  // injective on M_8 as well.
  products8 := [E[2]^4, E[2]^2*E[4], E[2]*E[6], E[4]^2, E[8]];
  assert #LinearDependence(products8) eq 0;
  assert #products8 eq Dimension(M8);

  M10 := HMFSpace(M, [10, 10, 10]);
  assert EisensteinDimension(M10) eq 1;
  assert CuspDimension(M10) eq 8;

  products10 := [E[2]^5, E[2]^3*E[4], E[2]^2*E[6], E[2]*E[4]^2, E[2]*E[8],
                 E[4]*E[6], E[10]];
  assert #LinearDependence(products10) eq 0;

  // Split-prime trace forms: full base precision, no Hecke division.
  ps13 := [fac[1] : fac in Factorization(13*ZF)];
  assert #ps13 eq 3;
  assert &and[Norm(pp) eq 13 : pp in ps13];
  PrecomputeTraceForms(M, ps13);
  T := [TraceForm(M10, pp) : pp in ps13];
  assert &and[Precision(t) eq prec : t in T];

  // Two split primes complete M_10; truncation is injective on M_10.
  assert #LinearDependence(products10 cat T[1..2]) eq 0;
  assert #products10 + 2 eq Dimension(M10);

  // The third split prime is dependent, exactly as with Hecke translates.
  // Its dependence is Galois-symmetric: e1 = T_1 + T_2 + T_3 is invariant and
  // lies in the Eisenstein-monomial span of M_10; the dependence vector below
  // is exact because truncation is injective on M_10.
  e1 := T[1] + T[2] + T[3];
  dep := LinearDependence([e1] cat products10);
  assert #dep eq 1;
  v := dep[1];
  assert v[1] ne 0;
  w := v[1] lt 0 select [-a : a in Eltseq(v)] else Eltseq(v);
  assert w eq [685308991651200, -77043333364867880775, 1579817724442250301030,
               -4300751463006555390880, -4792030832740917362883,
               9099773869074851707780, 8505396441101601977996,
               -10015162405506363352268];

  // The image of the 7-coordinate map is a threefold (Jacobian certificate).
  assert AlgebraicallyIndependent([E[2]^4, E[2]^2*E[4], E[2]*E[6], E[8]]);
  // The quadruple used by earlier versions is algebraically dependent.
  assert not AlgebraicallyIndependent(products8[1..4]);

  // The relation ideal of the model is zero in every degree <= 16: monomial
  // evaluations have full rank, which no truncation artifact can imitate.
  // In particular the degree-16 equations displayed by earlier versions of
  // this example are not relations.
  gens := [* E[2], E[4], E[6], E[8], E[10], T[1], T[2] *];
  Rpoly := ConstructWeightedPolynomialRing(gens);
  expected_free := [1, 2, 3, 5, 9, 12, 17, 24];
  for i in [1..8] do
    k := 2*i;
    mons := [m : m in MonomialsOfWeightedDegree(Rpoly, k)];
    assert #mons eq expected_free[i];
    ev := EvaluateMonomials(gens, mons);
    assert #LinearDependence(ev) eq 0;
  end for;

  // The same statement through the public API: the syzygy ideal of the model
  // in the degrees the old example displayed equations for is zero.
  assert #Basis(Syzygies(gens, [14, 16])) eq 0;
end procedure;

test_cyclic_cubic_threefold();
